version: "3.9"
services:
  api:
    build: ./api
    env_file: .env
    ports:
      - "8000:8000"
    volumes:
      - ./api:/app
      - ./data:/data
  web:
    image: nginx:alpine
    ports:
      - "5173:80"
    volumes:
      - ./web:/usr/share/nginx/html:ro
    depends_on:
      - api
